    /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Dlgbahasa_pasien.java
 *
 * Created on May 23, 2010, 1:25:13 AM
 */

package simrskhanza;

import fungsi.BackgroundMusic;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.FileInputStream;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author dosen
 */
public class DlgOperatorAntrian extends javax.swing.JDialog {
    private Connection koneksi=koneksiDB.condb();
    private sekuel Sequel=new sekuel();
    private validasi Valid = new validasi();
    private int i = 0, cekPang = 0, panggilan = 0, nomorpasien = 0, hasilantrian = 0;
    private String wktPanggil = "", wktAmbilNomor = "", panggilanFix = "", noPangAkhir = "", nomorDipanggil = "";
    private BackgroundMusic music;
    private String[] urut = {"", "./suara/satu.mp3", "./suara/dua.mp3", "./suara/tiga.mp3", "./suara/empat.mp3",
        "./suara/lima.mp3", "./suara/enam.mp3", "./suara/tujuh.mp3", "./suara/delapan.mp3",
        "./suara/sembilan.mp3", "./suara/sepuluh.mp3", "./suara/sebelas.mp3"};

    /** Creates new form Dlgbahasa_pasien
     * @param parent
     * @param modal */
    public DlgOperatorAntrian(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocation(10,10);
        setSize(459,539);
        
        try {
            cekRefreshAntri();
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        prosesTombol = new widget.ProgressBar();
        internalFrame1 = new widget.InternalFrame();
        panelGlass7 = new widget.panelisi();
        jLabel38 = new widget.Label();
        loket1 = new widget.RadioButton();
        loket2 = new widget.RadioButton();
        loket3 = new widget.RadioButton();
        loket4 = new widget.RadioButton();
        loket5 = new widget.RadioButton();
        loket6 = new widget.RadioButton();
        jLabel45 = new widget.Label();
        statusOperator = new widget.Label();
        panelGlass9 = new widget.panelisi();
        infoantrian = new widget.Label();
        BtnSimpanOperator = new widget.Button();
        BtnCekAudio = new widget.Button();
        BtnKeluar = new widget.Button();
        panelGlass11 = new widget.panelisi();
        panelGlass10 = new widget.panelisi();
        BtnPanggilan = new widget.ButtonBig();
        BtnUlangPanggilan = new widget.ButtonBig();
        panelGlass12 = new widget.panelisi();
        nomor = new widget.Label();

        prosesTombol.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        prosesTombol.setName("prosesTombol"); // NOI18N
        prosesTombol.setPreferredSize(new java.awt.Dimension(160, 40));
        prosesTombol.setStringPainted(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 3), "::[ Operator Antrian ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        panelGlass7.setName("panelGlass7"); // NOI18N
        panelGlass7.setPreferredSize(new java.awt.Dimension(44, 70));
        panelGlass7.setLayout(null);

        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Tentukan Pilihan Nomor Loket : ");
        jLabel38.setName("jLabel38"); // NOI18N
        panelGlass7.add(jLabel38);
        jLabel38.setBounds(0, 10, 170, 23);

        loket1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.pink));
        buttonGroup1.add(loket1);
        loket1.setText("1 (SATU)");
        loket1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        loket1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        loket1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        loket1.setName("loket1"); // NOI18N
        loket1.setPreferredSize(new java.awt.Dimension(95, 23));
        panelGlass7.add(loket1);
        loket1.setBounds(175, 10, 80, 23);

        loket2.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.pink));
        buttonGroup1.add(loket2);
        loket2.setText("2 (DUA)");
        loket2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        loket2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        loket2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        loket2.setName("loket2"); // NOI18N
        loket2.setPreferredSize(new java.awt.Dimension(95, 23));
        panelGlass7.add(loket2);
        loket2.setBounds(262, 10, 80, 23);

        loket3.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.pink));
        buttonGroup1.add(loket3);
        loket3.setText("3 (TIGA)");
        loket3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        loket3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        loket3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        loket3.setName("loket3"); // NOI18N
        loket3.setPreferredSize(new java.awt.Dimension(95, 23));
        panelGlass7.add(loket3);
        loket3.setBounds(349, 10, 80, 23);

        loket4.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.pink));
        buttonGroup1.add(loket4);
        loket4.setText("4 (EMPAT)");
        loket4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        loket4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        loket4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        loket4.setName("loket4"); // NOI18N
        loket4.setPreferredSize(new java.awt.Dimension(95, 23));
        panelGlass7.add(loket4);
        loket4.setBounds(436, 10, 80, 23);

        loket5.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.pink));
        buttonGroup1.add(loket5);
        loket5.setText("5 (LIMA)");
        loket5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        loket5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        loket5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        loket5.setName("loket5"); // NOI18N
        loket5.setPreferredSize(new java.awt.Dimension(95, 23));
        panelGlass7.add(loket5);
        loket5.setBounds(523, 10, 80, 23);

        loket6.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.pink));
        buttonGroup1.add(loket6);
        loket6.setText("6 (ENAM)");
        loket6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        loket6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        loket6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        loket6.setName("loket6"); // NOI18N
        loket6.setPreferredSize(new java.awt.Dimension(95, 23));
        panelGlass7.add(loket6);
        loket6.setBounds(610, 10, 80, 23);

        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("Status Operator : ");
        jLabel45.setName("jLabel45"); // NOI18N
        panelGlass7.add(jLabel45);
        jLabel45.setBounds(0, 38, 170, 23);

        statusOperator.setForeground(new java.awt.Color(0, 0, 0));
        statusOperator.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusOperator.setText("-");
        statusOperator.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        statusOperator.setName("statusOperator"); // NOI18N
        panelGlass7.add(statusOperator);
        statusOperator.setBounds(175, 38, 830, 23);

        internalFrame1.add(panelGlass7, java.awt.BorderLayout.PAGE_START);

        panelGlass9.setName("panelGlass9"); // NOI18N
        panelGlass9.setPreferredSize(new java.awt.Dimension(44, 44));
        panelGlass9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 9));

        infoantrian.setForeground(new java.awt.Color(0, 0, 0));
        infoantrian.setText("\" Selamat bekerja, awali dengan do'a & semangat melayani pasien \"");
        infoantrian.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        infoantrian.setName("infoantrian"); // NOI18N
        infoantrian.setPreferredSize(new java.awt.Dimension(620, 23));
        panelGlass9.add(infoantrian);

        BtnSimpanOperator.setForeground(new java.awt.Color(0, 0, 0));
        BtnSimpanOperator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/man1-24.png"))); // NOI18N
        BtnSimpanOperator.setMnemonic('O');
        BtnSimpanOperator.setText("Simpan Operator");
        BtnSimpanOperator.setToolTipText("Alt+O");
        BtnSimpanOperator.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnSimpanOperator.setIconTextGap(5);
        BtnSimpanOperator.setName("BtnSimpanOperator"); // NOI18N
        BtnSimpanOperator.setPreferredSize(new java.awt.Dimension(150, 23));
        BtnSimpanOperator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanOperatorActionPerformed(evt);
            }
        });
        panelGlass9.add(BtnSimpanOperator);

        BtnCekAudio.setForeground(new java.awt.Color(0, 0, 0));
        BtnCekAudio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/icons8-audio-24.png"))); // NOI18N
        BtnCekAudio.setMnemonic('U');
        BtnCekAudio.setText("Cek Audio");
        BtnCekAudio.setToolTipText("Alt+U");
        BtnCekAudio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnCekAudio.setIconTextGap(5);
        BtnCekAudio.setName("BtnCekAudio"); // NOI18N
        BtnCekAudio.setPreferredSize(new java.awt.Dimension(110, 23));
        BtnCekAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCekAudioActionPerformed(evt);
            }
        });
        panelGlass9.add(BtnCekAudio);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(90, 23));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass9.add(BtnKeluar);

        internalFrame1.add(panelGlass9, java.awt.BorderLayout.PAGE_END);

        panelGlass11.setName("panelGlass11"); // NOI18N
        panelGlass11.setPreferredSize(new java.awt.Dimension(44, 44));
        panelGlass11.setLayout(new java.awt.BorderLayout());

        panelGlass10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "[ Panggilan Antrian Pasien ] ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        panelGlass10.setName("panelGlass10"); // NOI18N
        panelGlass10.setPreferredSize(new java.awt.Dimension(44, 44));
        panelGlass10.setWarnaAtas(new java.awt.Color(204, 255, 255));
        panelGlass10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 8, 25));

        BtnPanggilan.setForeground(new java.awt.Color(0, 0, 0));
        BtnPanggilan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/iconfinder_user_warning_48813.png"))); // NOI18N
        BtnPanggilan.setText("PANGGIL ANTRIAN");
        BtnPanggilan.setIconTextGap(0);
        BtnPanggilan.setName("BtnPanggilan"); // NOI18N
        BtnPanggilan.setPreferredSize(new java.awt.Dimension(200, 120));
        BtnPanggilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPanggilanActionPerformed(evt);
            }
        });
        panelGlass10.add(BtnPanggilan);

        BtnUlangPanggilan.setForeground(new java.awt.Color(0, 0, 0));
        BtnUlangPanggilan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/system-software-update.png"))); // NOI18N
        BtnUlangPanggilan.setText("ULANGI PANGGILAN");
        BtnUlangPanggilan.setIconTextGap(0);
        BtnUlangPanggilan.setName("BtnUlangPanggilan"); // NOI18N
        BtnUlangPanggilan.setPreferredSize(new java.awt.Dimension(200, 120));
        BtnUlangPanggilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUlangPanggilanActionPerformed(evt);
            }
        });
        panelGlass10.add(BtnUlangPanggilan);

        panelGlass11.add(panelGlass10, java.awt.BorderLayout.CENTER);

        panelGlass12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "[ Nomor Panggilan Antrian ]", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        panelGlass12.setName("panelGlass12"); // NOI18N
        panelGlass12.setPreferredSize(new java.awt.Dimension(400, 44));
        panelGlass12.setWarnaBawah(new java.awt.Color(255, 255, 204));
        panelGlass12.setLayout(new java.awt.BorderLayout());

        nomor.setForeground(new java.awt.Color(0, 0, 0));
        nomor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomor.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        nomor.setName("nomor"); // NOI18N
        nomor.setPreferredSize(new java.awt.Dimension(250, 65));
        panelGlass12.add(nomor, java.awt.BorderLayout.CENTER);

        panelGlass11.add(panelGlass12, java.awt.BorderLayout.WEST);

        internalFrame1.add(panelGlass11, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            dispose();
        } 
}//GEN-LAST:event_BtnKeluarKeyPressed

    private void BtnSimpanOperatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanOperatorActionPerformed
        if (loket1.isSelected() == true) {
            akses.setNomorLoket("1");
        } else if (loket2.isSelected() == true) {
            akses.setNomorLoket("2");
        } else if (loket3.isSelected() == true) {
            akses.setNomorLoket("3");
        } else if (loket4.isSelected() == true) {
            akses.setNomorLoket("4");
        } else if (loket5.isSelected() == true) {
            akses.setNomorLoket("5");
        } else if (loket6.isSelected() == true) {
            akses.setNomorLoket("6");
        } else {
            akses.setNomorLoket("");
        }

        if (akses.getNomorLoket().equals("")) {
            statusOperator.setText("Anda belum menentukan no. loketnya.");
        } else if (loket1.isSelected() == false && loket2.isSelected() == false && loket3.isSelected() == false
                && loket4.isSelected() == false && loket5.isSelected() == false && loket6.isSelected() == false) {
            JOptionPane.showMessageDialog(null, "Anda belum menentukan no. loketnya, silahkan pilih dulu salah satu..!!");
        } else {
            statusOperator.setText("Anda terpilih melayani antrian pasien diloket " + akses.getNomorLoket());
        }
    }//GEN-LAST:event_BtnSimpanOperatorActionPerformed

    private void BtnCekAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCekAudioActionPerformed
        i = JOptionPane.showConfirmDialog(null, "Apakah cek audio/suara panggilan antrian pasien akan dilakukan...??", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            Sequel.mengedit("antrian_pemanggil", "status='proses' and date(waktu_panggil)=date(now())", "status='ok'");

            JOptionPane.showMessageDialog(null, "Perbaikan error audio/suara panggilan antrian pasien berhasil dilakukan, proses pemanggilan antrian bisa dilakukan lagi...!!");
        }
    }//GEN-LAST:event_BtnCekAudioActionPerformed

    private void BtnPanggilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPanggilanActionPerformed
        cekPang = 0;
        if (akses.getNomorLoket().equals("1") || akses.getNomorLoket().equals("2")
                || akses.getNomorLoket().equals("3") || akses.getNomorLoket().equals("4")
                || akses.getNomorLoket().equals("5") || akses.getNomorLoket().equals("6")) {
            cekPang = Sequel.cariInteger("select count(-1) from antrian_pemanggil where status='proses' and date(waktu_panggil)=date(now())");

            if (infoantrian.getText().equals("Hari ini masih belum ada pasien.")) {
                JOptionPane.showMessageDialog(null, "Belum ada pasien yang mengambil nomor antrian,...!!");
            } else if (cekPang > 0) {
                JOptionPane.showMessageDialog(null, "Loket lain masih memanggil antrian, tunggu sebentar,...!!");
            } else if (infoantrian.getText().equals("Antrian pasien rawat jalan sudah habis.")) {
                JOptionPane.showMessageDialog(null, "Hentikan panggilan antrian pasien karena sudah habis dilayani, terima kasih...!!");
            } else {
                tambahPanggilan();
                suaraPanggilan();
                Sequel.mengedit("antrian_pemanggil", "status='proses' and date(waktu_panggil)=date(now())", "status='ok'");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Silahkan tentukan dulu nomor loketnya utk. melakukan panggilan antrian & simpan sbg. operator..!!");
        }
    }//GEN-LAST:event_BtnPanggilanActionPerformed

    private void BtnUlangPanggilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUlangPanggilanActionPerformed
        cekPang = 0;

        if (akses.getNomorLoket().equals("1") || akses.getNomorLoket().equals("2")
                || akses.getNomorLoket().equals("3") || akses.getNomorLoket().equals("4")
                || akses.getNomorLoket().equals("5") || akses.getNomorLoket().equals("6")) {
            cekPang = Sequel.cariInteger("select count(-1) from antrian_pemanggil where status='proses' and date(waktu_panggil)=date(now())");

            if (infoantrian.getText().equals("Hari ini masih belum ada pasien.")) {
                JOptionPane.showMessageDialog(null, "Belum ada pasien yang mengambil nomor antrian,...!!");
            } else if (cekPang > 0) {
                JOptionPane.showMessageDialog(null, "Loket lain masih memanggil antrian, tunggu sebentar,...!!");
            } else if (infoantrian.getText().contains("Masih ada") == true && nomor.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Lakukan panggilan dulu, kemudian panggilannya baru bisa diulangi...!!");
            } else {
                Sequel.mengedit("antrian_pemanggil", "no_antrian='" + Sequel.cariIsi("SELECT no_antrian FROM antrian_pemanggil where date(waktu_panggil)=date(now()) ORDER BY no_antrian DESC LIMIT 1") + "'",
                        "status='proses'");
                suaraPanggilan();
                Sequel.mengedit("antrian_pemanggil", "no_antrian='" + Sequel.cariIsi("SELECT no_antrian FROM antrian_pemanggil where date(waktu_panggil)=date(now()) ORDER BY no_antrian DESC LIMIT 1") + "'",
                        "status='ok'");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Silahkan tentukan dulu nomor loketnya utk. melakukan panggilan antrian & simpan sbg. operator..!!");
        }
    }//GEN-LAST:event_BtnUlangPanggilanActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (akses.getNomorLoket().equals("")) {
            statusOperator.setText("Anda belum menentukan no. loketnya.");
        } else {
            statusOperator.setText("Anda terpilih melayani antrian pasien diloket " + akses.getNomorLoket());
        }
        akses.tRefreshAntri.start();
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgOperatorAntrian dialog = new DlgOperatorAntrian(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnCekAudio;
    private widget.Button BtnKeluar;
    private widget.ButtonBig BtnPanggilan;
    private widget.Button BtnSimpanOperator;
    private widget.ButtonBig BtnUlangPanggilan;
    private javax.swing.ButtonGroup buttonGroup1;
    private widget.Label infoantrian;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel38;
    private widget.Label jLabel45;
    private widget.RadioButton loket1;
    private widget.RadioButton loket2;
    private widget.RadioButton loket3;
    private widget.RadioButton loket4;
    private widget.RadioButton loket5;
    private widget.RadioButton loket6;
    private widget.Label nomor;
    private widget.panelisi panelGlass10;
    private widget.panelisi panelGlass11;
    private widget.panelisi panelGlass12;
    private widget.panelisi panelGlass7;
    private widget.panelisi panelGlass9;
    private widget.ProgressBar prosesTombol;
    private widget.Label statusOperator;
    // End of variables declaration//GEN-END:variables

    private void tambahPanggilan() {
        wktPanggil = "";
        wktAmbilNomor = "";
        panggilanFix = "";
        noPangAkhir = "";
        nomorDipanggil = "";
        wktPanggil = Sequel.cariIsi("select now()");
        nomorDipanggil = Sequel.cariIsi("select ifnull(MAX(no_antrian)+1,1) from antrian_pemanggil where date(waktu_panggil)=date(now())");

        if (akses.getNomorLoket().equals("1")) {
            Sequel.menyimpan("antrian_pemanggil", "'" + nomorDipanggil + "','proses','1','" + wktPanggil + "'", "Nomor Panggilan Antrian");
            noPangAkhir = Sequel.cariIsi("select no_antrian from antrian_pemanggil where date(waktu_panggil)=date(now()) order by no_antrian desc limit 1");
            wktAmbilNomor = Sequel.cariIsi("select waktu_cetak from antrian_nomor where no_antrian='" + noPangAkhir + "' and date(waktu_cetak)=date(now())");
            panggilanFix = noPangAkhir;
            akses.setNomorAntrian(nomorDipanggil);
        } else if (akses.getNomorLoket().equals("2")) {
            Sequel.menyimpan("antrian_pemanggil", "'" + nomorDipanggil + "','proses','2','" + wktPanggil + "'", "Nomor Panggilan Antrian");
            noPangAkhir = Sequel.cariIsi("select no_antrian from antrian_pemanggil where date(waktu_panggil)=date(now()) order by no_antrian desc limit 1");
            wktAmbilNomor = Sequel.cariIsi("select waktu_cetak from antrian_nomor where no_antrian='" + noPangAkhir + "' and date(waktu_cetak)=date(now())");
            panggilanFix = noPangAkhir;
            akses.setNomorAntrian(nomorDipanggil);
        } else if (akses.getNomorLoket().equals("3")) {
            Sequel.menyimpan("antrian_pemanggil", "'" + nomorDipanggil + "','proses','3','" + wktPanggil + "'", "Nomor Panggilan Antrian");
            noPangAkhir = Sequel.cariIsi("select no_antrian from antrian_pemanggil where date(waktu_panggil)=date(now()) order by no_antrian desc limit 1");
            wktAmbilNomor = Sequel.cariIsi("select waktu_cetak from antrian_nomor where no_antrian='" + noPangAkhir + "' and date(waktu_cetak)=date(now())");
            panggilanFix = noPangAkhir;
            akses.setNomorAntrian(nomorDipanggil);
        } else if (akses.getNomorLoket().equals("4")) {
            Sequel.menyimpan("antrian_pemanggil", "'" + nomorDipanggil + "','proses','4','" + wktPanggil + "'", "Nomor Panggilan Antrian");
            noPangAkhir = Sequel.cariIsi("select no_antrian from antrian_pemanggil where date(waktu_panggil)=date(now()) order by no_antrian desc limit 1");
            wktAmbilNomor = Sequel.cariIsi("select waktu_cetak from antrian_nomor where no_antrian='" + noPangAkhir + "' and date(waktu_cetak)=date(now())");
            panggilanFix = noPangAkhir;
            akses.setNomorAntrian(nomorDipanggil);
        } else if (akses.getNomorLoket().equals("5")) {
            Sequel.menyimpan("antrian_pemanggil", "'" + nomorDipanggil + "','proses','5','" + wktPanggil + "'", "Nomor Panggilan Antrian");
            noPangAkhir = Sequel.cariIsi("select no_antrian from antrian_pemanggil where date(waktu_panggil)=date(now()) order by no_antrian desc limit 1");
            wktAmbilNomor = Sequel.cariIsi("select waktu_cetak from antrian_nomor where no_antrian='" + noPangAkhir + "' and date(waktu_cetak)=date(now())");
            panggilanFix = noPangAkhir;
            akses.setNomorAntrian(nomorDipanggil);
        } else if (akses.getNomorLoket().equals("6")) {
            Sequel.menyimpan("antrian_pemanggil", "'" + nomorDipanggil + "','proses','6','" + wktPanggil + "'", "Nomor Panggilan Antrian");
            noPangAkhir = Sequel.cariIsi("select no_antrian from antrian_pemanggil where date(waktu_panggil)=date(now()) order by no_antrian desc limit 1");
            wktAmbilNomor = Sequel.cariIsi("select waktu_cetak from antrian_nomor where no_antrian='" + noPangAkhir + "' and date(waktu_cetak)=date(now())");
            panggilanFix = noPangAkhir;
            akses.setNomorAntrian(nomorDipanggil);
        }
    }
    
    private void suaraPanggilan() {
        try {
            music = new BackgroundMusic("./suara/intro_rawat_jalan_nirwana.mp3");
            music.start();

            BtnPanggilan.setEnabled(false);
            BtnUlangPanggilan.setEnabled(false);

            Thread.sleep(3500);
            panggilAntrian(Integer.parseInt(Sequel.cariIsi("select no_antrian from antrian_pemanggil where date(waktu_panggil)=date(now()) order by no_antrian desc limit 1")));
            music = new BackgroundMusic("./suara/diloket.mp3");
            music.start();
            Thread.sleep(1000);
            panggilAntrian(Integer.parseInt(akses.getNomorLoket()));

            persenTombolPanggilan();
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }
    
    private void panggilAntrian(int antrian) {
        if (antrian < 12) {
            try {
                music = new BackgroundMusic(urut[antrian]);
                music.start();
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                System.out.println(ex);
            }
        } else if (antrian < 20) {
            try {
                music = new BackgroundMusic(urut[antrian - 10]);
                music.start();
                Thread.sleep(700);
            } catch (InterruptedException ex) {
                System.out.println(ex);
            }

            try {
                music = new BackgroundMusic("./suara/belas.mp3");
                music.start();
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                System.out.println(ex);
            }
        } else if (antrian < 100) {
            try {
                music = new BackgroundMusic(urut[antrian / 10]);
                music.start();
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                System.out.println(ex);
            }

            try {
                music = new BackgroundMusic("./suara/puluh.mp3");
                music.start();
                Thread.sleep(600);
            } catch (InterruptedException ex) {
                System.out.println(ex);
            }

            panggilAntrian(antrian % 10);
        } else if (antrian < 200) {
            try {
                music = new BackgroundMusic("./suara/seratus.mp3");
                music.start();
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                System.out.println(ex);
            }

            panggilAntrian(antrian - 100);
        } else if (antrian < 1000) {
            panggilAntrian(antrian / 100);

            try {
                music = new BackgroundMusic("./suara/ratus.mp3");
                music.start();
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                System.out.println(ex);
            }

            panggilAntrian(antrian % 100);
        }
    }
    
    private void persenTombolPanggilan() {
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                //proses bar diatur 30%. nilai i < 31 hasilnya 30%
                for (int i = 0; i < 31; i++) {
                    try {
                        prosesTombol.setValue(i);
                        Thread.sleep(30);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(DlgOperatorAntrian.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

                if (prosesTombol.getString().equals("30%")) {
                    BtnPanggilan.setEnabled(true);
                    BtnUlangPanggilan.setEnabled(true);
                }
            }
        });

        t.start();
    }
    
    public void isCek() {
        BtnSimpanOperator.setEnabled(akses.getregistrasi());
        BtnCekAudio.setEnabled(akses.getregistrasi());
        BtnPanggilan.setEnabled(akses.getregistrasi());
        BtnUlangPanggilan.setEnabled(akses.getregistrasi());
        
        if (akses.getNomorLoket().equals("1")) {
            loket1.setSelected(true);
            loket2.setSelected(false);
            loket3.setSelected(false);
            loket4.setSelected(false);
            loket5.setSelected(false);
            loket6.setSelected(false);
        } else if (akses.getNomorLoket().equals("2")) {
            loket1.setSelected(false);
            loket2.setSelected(true);
            loket3.setSelected(false);
            loket4.setSelected(false);
            loket5.setSelected(false);
            loket6.setSelected(false);
        } else if (akses.getNomorLoket().equals("3")) {
            loket1.setSelected(false);
            loket2.setSelected(false);
            loket3.setSelected(true);
            loket4.setSelected(false);
            loket5.setSelected(false);
            loket6.setSelected(false);
        } else if (akses.getNomorLoket().equals("4")) {
            loket1.setSelected(false);
            loket2.setSelected(false);
            loket3.setSelected(false);
            loket4.setSelected(true);
            loket5.setSelected(false);
            loket6.setSelected(false);
        } else if (akses.getNomorLoket().equals("5")) {
            loket1.setSelected(false);
            loket2.setSelected(false);
            loket3.setSelected(false);
            loket4.setSelected(false);
            loket5.setSelected(true);
            loket6.setSelected(false);
        } else if (akses.getNomorLoket().equals("6")) {
            loket1.setSelected(false);
            loket2.setSelected(false);
            loket3.setSelected(false);
            loket4.setSelected(false);
            loket5.setSelected(false);
            loket6.setSelected(true);
        }
    }
    
    public void emptTeks() {
        buttonGroup1.clearSelection();
    }
    
    private void cekRefreshAntri() {
        ActionListener taskPerformer = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                nomor.setText(Sequel.cariIsi("SELECT ifnull(no_antrian,'-') FROM antrian_pemanggil where date(waktu_panggil)=date(now()) ORDER BY no_antrian DESC LIMIT 1"));
                cekAntrian();
            }
        };
        // Timer
        //interval 1000 ms = 1 detik
        //interval 30000 ms = 30 detik atau setngah menit
        akses.tRefreshAntri = new Timer(1000, taskPerformer);
    }
    
    private void cekAntrian() {
        panggilan = 0;
        nomorpasien = 0;
        hasilantrian = 0;

        //cek nomor antrian pasien
        if (Sequel.cariIsi("select no_antrian from antrian_nomor where date(waktu_cetak)=date(now()) order by no_antrian desc limit 1").equals("")) {
            nomorpasien = 0;
        } else {
            nomorpasien = Integer.parseInt(Sequel.cariIsi("select no_antrian from antrian_nomor where date(waktu_cetak)=date(now()) order by no_antrian desc limit 1"));
        }

        //cek nomor panggilan pasien
        if (Sequel.cariIsi("SELECT no_antrian FROM antrian_pemanggil where date(waktu_panggil)=date(now()) ORDER BY no_antrian DESC LIMIT 1").equals("")) {
            panggilan = 0;
        } else {
            panggilan = Integer.parseInt(Sequel.cariIsi("select no_antrian from antrian_pemanggil where date(waktu_panggil)=date(now()) order by no_antrian desc limit 1"));
        }

        if (panggilan == 0 && nomorpasien == 0) {
            infoantrian.setText("Hari ini masih belum ada pasien.");
        } else {
            infoantrian.setText("Antrian terakhir pasien adalah nomor : " + nomorpasien + "");

            //hasil hitungan antrian
            hasilantrian = nomorpasien - panggilan;
            if (nomorpasien > panggilan) {
                infoantrian.setText("Ada antrian pasien rawat jalan yang belum dipanggil & dilayani oleh petugas pendaftaran.");
            }

            if (hasilantrian >= 1) {
                infoantrian.setText("Masih ada : " + hasilantrian + " orang lagi yang belum dipanggil & dilayani oleh petugas pendaftaran pasien rawat jalan.");
            }

            if (hasilantrian < 1) {
                infoantrian.setText("Antrian pasien rawat jalan sudah habis.");
            }

            if (panggilan > nomorpasien) {
                infoantrian.setText("Ada antrian pasien rawat jalan yang terlewati dari panggilan operator.");
            }
        }
    }
}
